name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: danscorah/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml

      - name: Configure git
        run: |
          git config --global user.name "danscorah"
          git config --global user.email "danscorah@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://danscorah:${PAT_TOKEN}@github.com" > ~/.git-credentials
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Debug and commit changes
        run: |
          echo "Token length: ${#PAT_TOKEN}"
          echo "Current remote URL:"
          git remote -v
          git add .
          git commit -m "Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}"
          # Set the remote URL with token
          git remote set-url origin https://danscorah:${PAT_TOKEN}@github.com/danscorah/python-app.git
          echo "New remote URL:"
          git remote -v
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
